### ISSUE TITLE
Installation error with older versions of Node

### ISSUE THREAD

**Issue by BrizzleRocker** [fourkitchens/emulsify-gulp#81] opened 2018-06-25 11:30 UTC
I have a new starter today who has cloned our repo and is running `npm start` after doing the `npm install` but unfortunately is getting nothing but errors! The first appears to be syntax related as shown below:

```
npm info lifecycle emulsify@1.0.0~start: Failed to exec start script
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! emulsify@1.0.0 start: `gulp clean && gulp compile && gulp theme`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the emulsify@1.0.0 start script 'gulp clean && gulp compile && gulp theme'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the emulsify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp clean && gulp compile && gulp theme
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs emulsify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls emulsify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/docroot/sites/[my_site]/themes/custom/PatternLab[my_site]_emulsify/npm-debug.log
root@8e38628cbbdd:/var/www/html/docroot/sites/[my_site]/themes/custom/PatternLab[my_site]_emulsify# ./node_modules/.bin/gulp build
/var/www/html/docroot/sites/[my_site]/themes/custom/PatternLab[my_site]_emulsify/node_modules/emulsify-gulp/index.js:54
      )
      ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /var/www/html/docroot/sites/[my_site]/themes/custom/PatternLab[my_site]_emulsify/gulpfile.js:16:3
    at Object.<anonymous> (/var/www/html/docroot/sites/[my_site]/themes/custom/PatternLab[my_site]_emulsify/gulpfile.js:18:3)
```

**Comment by ModulesUnraveled** [comment] 2018-06-25 12:33
I see a bunch of `my_site`s in that output. Are they renaming the site correctly?

Also, do they have node and npm installed. 

If all else fails, please provide the steps to reproduce. 

Thanks

**Comment by BrizzleRocker** [comment] 2018-06-25 12:48
@ModulesUnraveled I have obfuscated the true path hence the `[my_site]` you are seeing. Please ignore and imagine a correct path in there.

Having stated they've run `npm install` I would've thought that your next question was slightly superfluous but yes, node version 7.1.0 and npm 3.10.9 in the docker container.

Manually editing the index.js located in /node_modules/emulsify-gulp/ fixes this error so I am of the opinion there is a break in the current release to do with the syntax in `/node_modules/emulsify-gulp/index.js` at line 54.

**Comment by BrizzleRocker** [comment] 2018-06-25 14:09
![linterrors](https://user-images.githubusercontent.com/7765674/41855089-aef7bf12-7889-11e8-8459-18f67b262c2b.PNG)

**Comment by evanmwillhite** [comment] 2018-06-25 14:23
@BrizzleRocker I am not getting these errors running the installation process in the README (either via `npm` or `yarn`), but it sounds like this situation may be a little different than a brand new Emulsify install. It sounds like this may be an existing emulsify copy that is being installed? Basically, it looks like a straight-forward syntax issue, but it could also be dependency issues that have changed since this installation was originally installed that are throwing these errors. 

This may be a long shot, but can you provide us the emulsify repo to troubleshoot? Still working on debugging from my end, but thought I'd ask.

**Comment by crashspringfield** [comment] 2018-06-25 16:58
Steps to reproduce:
1. Have a working site that uses Emulsify
2. Make sure to have built that site [before proper semantic versioning was used](https://github.com/fourkitchens/emulsify/commit/c648321947e2473578bc862ee958aca7a026ed9f)
3. Try building site again and realize breaking changes were introduced.

**Comment by crashspringfield** [comment] 2018-06-25 17:00
@BrizzleRocker My team's site broke the same way. Locally I've had luck fixing the issue with Node 10+ (I guess their error parsing got better) but unfortunately we can only use LTS versions on our build server Node 8, so this is still an issue for our team as well.

**Comment by crashspringfield** [comment] 2018-06-25 17:04
@evanmwillhite The issue is the comma on line 53. The babel function is being passed into the pipe function, which takes one argument. Removing the comma will solve the issue.

**Comment by evanmwillhite** [comment] 2018-06-25 17:09
@crashspringfield this is super helpful, thank you. My problem was that I tried installing older versions of Emulsify earlier today ([before we pinned versions of emulsify gulp](https://github.com/fourkitchens/emulsify/blob/v2.0.0/package.json#L6)) thinking that would help me debug, but I still couldn't recreate. @BrizzleRocker can you confirm the solution above fixes your team's issues? If so, we'll get a patch in asap.

**Comment by crashspringfield** [comment] 2018-06-25 18:00
@evanmwillhite I removed the comma(s) from `/node_modules/emulsify-gulp/index.js` and ran a test install on my site that was breaking with LTS (Node 8.9.0, NPM 5.5.1). I also tried with the versions @BrizzleRocker was using (7.1.0 and3.10). 

It looks like there is more than one syntax issue, but after removing all of the unecessary commas, I was able to get it to work. The trailing commas need removed from lines 53, 66, 86, 173.

It looks like [trailing commas in function syntax](https://node.green/#ES2017-features-trailing-commas-in-function-syntaxl) were introduced in Node 8.2.1.

**Comment by BrizzleRocker** [comment] 2018-06-26 07:15
Thanks for all the feedback. The container was 2 years old from this article https://savaslabs.com/2017/02/20/drupal-docker-pattern-lab.html and hadn't been updated.

We've decided to remove this container and compile locally on the hosted code (and update to the most recent Node LTS 8.11 and npm 5.6.0)

**Comment by evanmwillhite** [comment] 2018-06-26 14:11
Awesome, glad you got things working. I'm still going to leave this open in case we decide to remove those commas in favor of some older Node versions.

**Comment by BrizzleRocker** [comment] 2018-06-29 14:46
This still doesn't work on node v8.10.0 with npm 5.6.0

**Comment by ModulesUnraveled** [comment] 2018-06-29 14:55
Everything works for me on node v8.11.1 and npm 5.6.0

**Comment by crashspringfield** [comment] 2018-07-01 15:54
Since it seems to be an issue arising from unnecessary syntax, it'd probably be best to just remove the trailing commas. I'd be down to for the project and take this on.

**Comment by crashspringfield** [comment] 2018-07-07 14:06
I took out a pull request because I'd already solved this issue for my team. #83

**Comment by BrizzleRocker** [comment] 2018-07-09 07:18
@crashspringfield looks great - thanks for doing that.

**Comment by evanmwillhite** [comment] 2018-08-07 18:40
This was [merged](https://github.com/fourkitchens/emulsify-gulp/commit/f0d6a7eafa1662b9cc36989931c1c50d52ab5661) and I've also just changed our [eslintrc](https://github.com/fourkitchens/emulsify-gulp/pull/77/files#diff-0378d5111ab996d5882f4712e9350604) to not flag those during development. We will do a release soon to get those out.

**Closed by evanmwillhite** 2018-08-07 18:40 UTC
Labels: Priority: Low, Type: Bug
